apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: abhinay-ms
  description: A Flask microservice with CI/CD and observability
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: abhinayrimil/abhinay-ms
    backstage.io/techdocs-ref: dir:.
    prometheus.io/scrape: "true"
    loki.io/logs: "true"
spec:
  type: service
  lifecycle: experimental
  owner: platform-team

