apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Team owning microservices and platform infra
spec:
  type: team
  profile:
    displayName: Platform Team
  children: []         # Optional: list of child groups
  members:
    - abhinay           # References the user entity's metadata.name

